apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ansibledb.fullname" . }}
  labels:
    {{- include "ansibledb.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.ansibledb.admin.password | b64enc }}
  mongodb-password: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  {{- if  .Values.ansibledb.ldap.fid_password }}
  ldap-fid-password: {{ .Values.ansibledb.ldap.fid_password | b64enc }}
  {{- end }}
